version: 0.2

phases:
  install:
    runtime-versions:
      php: latest
  build:
    commands:
      - composer install
artifacts:
  type: zip
  files:
    - '**/*'
cache:
  paths:
    - 'vendor/**/*'
