version: 0.2

phases:
  install:
    runtime-versions:
      php: latest
  build:
    commands:
      - php -v
      - echo Build started on `date`
      - composer install

artifacts:
  type: zip
  files:
    - '**/*'
